import type { Exercicio, GrupoMuscular, Equipamento } from './types'

/** [nome, grupo, equipamento, execucao(|), erros(|), secundarios(,)] */
type Linha = [string, GrupoMuscular, Equipamento, string, string, string?]

const L: Linha[] = [
  /* ---------------------------- PEITO ---------------------------- */
  ['Supino reto com barra', 'peito', 'barra',
    'Deite no banco com os pes firmes no chao e escapulas retraidas (peito estufado).|Pegada um pouco mais aberta que os ombros. Tire a barra e estabilize sobre o peito.|Desca controlado ate encostar de leve na linha dos mamilos, cotovelos a ~45 graus do tronco.|Empurre ate estender os cotovelos sem travar, mantendo as escapulas presas.',
    'Quicar a barra no peito.|Abrir os cotovelos a 90 graus (machuca o ombro).|Levantar o quadril do banco.', 'triceps,ombro'],
  ['Supino inclinado com barra', 'peito', 'barra',
    'Banco entre 30 e 45 graus. Escapulas retraidas, pes firmes.|Desca a barra na altura da clavicula alta, controlado.|Empurre para cima e levemente para tras, sobre os ombros.',
    'Inclinacao acima de 45 graus vira exercicio de ombro.|Descer a barra muito baixa, no meio do peito.', 'ombro,triceps'],
  ['Supino declinado com barra', 'peito', 'barra',
    'Banco declinado, pes travados. Escapulas retraidas.|Desca a barra na parte baixa do peito.|Empurre ate quase estender, sem travar o cotovelo.',
    'Descer rapido demais sem controle.', 'triceps'],
  ['Supino reto com halteres', 'peito', 'halter',
    'Deite com um halter em cada mao sobre o peito, palmas para frente.|Desca ate os halteres ficarem na linha do peito, sentindo o alongamento.|Empurre juntando levemente os halteres no topo, sem bater um no outro.',
    'Descer demais e forcar a articulacao do ombro.|Bater os halteres no topo e perder a tensao.', 'triceps,ombro'],
  ['Supino inclinado com halteres', 'peito', 'halter',
    'Banco a 30-45 graus, halteres na altura do peito alto.|Desca controlado ate sentir o peitoral alongar.|Empurre para cima em arco leve, contraindo o peito no topo.',
    'Deixar os cotovelos caírem para tras da linha do corpo.', 'ombro,triceps'],
  ['Crucifixo reto com halteres', 'peito', 'halter',
    'Deitado, bracos estendidos acima do peito com cotovelos levemente flexionados.|Abra os bracos em arco ate sentir o alongamento do peitoral.|Feche o arco imaginando abracar uma arvore, sem dobrar mais os cotovelos.',
    'Transformar em supino dobrando os cotovelos.|Usar carga alta demais e perder a amplitude.', ''],
  ['Crucifixo inclinado com halteres', 'peito', 'halter',
    'Banco a 30 graus. Bracos estendidos, cotovelos semi-flexionados.|Abra em arco ate a linha do peito.|Feche contraindo a parte superior do peitoral.',
    'Descer alem do confortavel para o ombro.', ''],
  ['Crossover polia alta', 'peito', 'cabo',
    'Polias na posicao alta, um passo a frente, tronco levemente inclinado.|Puxe as maos para baixo e para dentro, cruzando na altura do quadril.|Contraia 1 segundo e volte controlado.',
    'Usar impulso do tronco.|Nao controlar a fase excentrica.', ''],
  ['Crossover polia baixa', 'peito', 'cabo',
    'Polias embaixo, pegada por baixo. Um passo a frente.|Suba as maos em arco ate a altura do peito, juntando na frente.|Contraia a parte superior do peito e volte devagar.',
    'Dobrar os cotovelos e virar rosca.', ''],
  ['Voador / Peck deck', 'peito', 'maquina',
    'Ajuste o banco para as maos ficarem na linha do peito.|Costas coladas no encosto, ombros para baixo.|Feche os bracos contraindo o peito, segure 1 segundo, volte controlado.',
    'Deixar o ombro rolar para frente.|Abrir demais e forcar a articulacao.', ''],
  ['Supino na maquina', 'peito', 'maquina',
    'Ajuste o assento para as pegadas ficarem na linha do peito.|Escapulas retraidas contra o encosto.|Empurre ate quase estender e volte controlado.',
    'Assento alto demais, transformando em exercicio de ombro.', 'triceps'],
  ['Flexao de braco', 'peito', 'peso-corporal',
    'Maos um pouco mais abertas que os ombros, corpo em linha reta da cabeca ao calcanhar.|Desca ate o peito quase encostar no chao, cotovelos a 45 graus.|Empurre o chao para longe mantendo o abdomen contraido.',
    'Deixar o quadril cair (lombar arqueada).|Abrir os cotovelos a 90 graus.', 'triceps,abdomen'],
  ['Flexao com pes elevados', 'peito', 'peso-corporal',
    'Pes num banco, maos no chao mais abertas que os ombros.|Corpo em linha reta, desca controlado.|Empurre focando na parte superior do peito.',
    'Perder o alinhamento do quadril.', 'ombro,triceps'],
  ['Mergulho nas paralelas', 'peito', 'peso-corporal',
    'Nas paralelas, incline o tronco para frente ~30 graus (foco peito).|Desca ate os ombros ficarem na linha dos cotovelos.|Empurre para cima sem travar os cotovelos.',
    'Descer alem da amplitude confortavel do ombro.|Ficar totalmente vertical (vira triceps).', 'triceps,ombro'],
  ['Pullover com halter', 'peito', 'halter',
    'Deitado no banco, segure um halter com as duas maos acima do peito.|Leve o halter para tras da cabeca com cotovelos semi-flexionados.|Volte contraindo peito e serratil.',
    'Dobrar demais os cotovelos.|Arquear a lombar.', 'costas'],

  /* ---------------------------- COSTAS ---------------------------- */
  ['Barra fixa pronada', 'costas', 'peso-corporal',
    'Pegada pronada, um pouco mais aberta que os ombros.|Puxe o peito em direcao a barra, iniciando pelas escapulas.|Desca controlado ate quase estender os cotovelos.',
    'Usar impulso de perna (kipping) sem necessidade.|Nao descer completamente.', 'biceps'],
  ['Barra fixa supinada', 'costas', 'peso-corporal',
    'Pegada supinada na largura dos ombros.|Puxe levando o peito a barra, cotovelos junto ao corpo.|Desca controlado ate estender.',
    'Balancar o corpo para compensar.', 'biceps'],
  ['Puxada frontal na polia', 'costas', 'cabo',
    'Pegada pronada aberta, coxas travadas no apoio.|Incline o tronco ~15 graus para tras e puxe a barra ate o peito alto.|Inicie o movimento deprimindo as escapulas, nao puxando com o braco.',
    'Puxar atras da nuca (risco para o ombro).|Jogar o tronco para tras usando impulso.', 'biceps'],
  ['Puxada supinada na polia', 'costas', 'cabo',
    'Pegada supinada na largura dos ombros.|Puxe a barra ate a parte alta do abdomen, cotovelos rentes ao corpo.|Volte controlado ate estender.',
    'Encurtar a amplitude no topo.', 'biceps'],
  ['Puxada com triangulo', 'costas', 'cabo',
    'Pegada neutra no triangulo, tronco levemente inclinado.|Puxe ate o peito, juntando as escapulas.|Segure 1 segundo e volte controlado.',
    'Encolher os ombros durante a puxada.', 'biceps'],
  ['Remada curvada com barra', 'costas', 'barra',
    'Pes na largura do quadril, joelhos semi-flexionados, tronco a ~45 graus.|Coluna neutra, olhar para o chao a frente.|Puxe a barra ate o umbigo, cotovelos para tras.|Desca controlado sem arredondar a lombar.',
    'Arredondar a coluna (risco alto de lesao).|Subir o tronco a cada repeticao.', 'biceps,lombar'],
  ['Remada curvada supinada', 'costas', 'barra',
    'Pegada supinada, tronco a 45 graus, coluna neutra.|Puxe a barra ate a parte baixa do abdomen.|Cotovelos colados no corpo, contraia e volte.',
    'Perder a neutralidade da coluna.', 'biceps'],
  ['Remada unilateral com halter', 'costas', 'halter',
    'Joelho e mao no banco, o outro pe firme no chao. Coluna neutra.|Puxe o halter em direcao ao quadril, cotovelo rente ao corpo.|Desca ate estender o braco, sentindo o dorsal alongar.',
    'Torcer o tronco para levantar mais carga.|Puxar so com o braco, sem mover a escapula.', 'biceps'],
  ['Remada baixa no cabo', 'costas', 'cabo',
    'Sentado, pes apoiados, joelhos semi-flexionados, coluna neutra.|Puxe o triangulo ate o umbigo, juntando as escapulas.|Volte deixando as escapulas se afastarem, sem arredondar a lombar.',
    'Balancar o tronco para frente e para tras.', 'biceps'],
  ['Remada cavalinho (T-bar)', 'costas', 'barra',
    'Tronco inclinado sobre a barra, peito apoiado se houver suporte.|Puxe a barra ate tocar o abdomen.|Contraia as escapulas no topo e desca controlado.',
    'Usar impulso de quadril.', 'biceps'],
  ['Remada na maquina', 'costas', 'maquina',
    'Peito apoiado no suporte, escapulas soltas na posicao inicial.|Puxe as pegadas ate a linha do abdomen.|Segure a contracao e volte controlado.',
    'Descolar o peito do apoio.', 'biceps'],
  ['Pulldown com bracos estendidos', 'costas', 'cabo',
    'Em pe de frente para a polia alta, bracos estendidos a frente.|Cotovelos travados semi-flexionados, empurre a barra ate as coxas.|Contraia o dorsal e volte controlado.',
    'Dobrar os cotovelos (vira triceps).', ''],
  ['Levantamento terra', 'costas', 'barra',
    'Pes na largura do quadril, barra sobre o meio do pe.|Quadril para tras, peito alto, coluna neutra, bracos estendidos.|Empurre o chao com as pernas e estenda o quadril ate ficar em pe.|Desca fazendo o caminho inverso, barra rente as pernas.',
    'Arredondar a lombar.|Puxar com os bracos em vez de empurrar com as pernas.|Hiperextender a lombar no topo.', 'posterior,gluteo,lombar'],
  ['Encolhimento com halteres', 'costas', 'halter',
    'Em pe, um halter em cada mao ao lado do corpo.|Eleve os ombros em direcao as orelhas, sem dobrar os cotovelos.|Segure 1 segundo no topo e desca controlado.',
    'Rolar os ombros (nao adiciona nada e desgasta a articulacao).', ''],

  /* ---------------------------- OMBRO ---------------------------- */
  ['Desenvolvimento militar com barra', 'ombro', 'barra',
    'Em pe ou sentado, barra na altura da clavicula, pegada pouco mais aberta que os ombros.|Abdomen contraido, gluteos ativos, sem arquear a lombar.|Empurre a barra acima da cabeca, terminando com ela sobre as orelhas.|Desca controlado ate o queixo.',
    'Arquear a lombar para empurrar.|Nao passar a cabeca (barra fica a frente).', 'triceps'],
  ['Desenvolvimento com halteres', 'ombro', 'halter',
    'Sentado com encosto, halteres na altura das orelhas, palmas para frente.|Empurre para cima ate quase estender, aproximando os halteres.|Desca controlado ate o cotovelo formar 90 graus.',
    'Bater os halteres no topo.|Descer alem do confortavel.', 'triceps'],
  ['Desenvolvimento Arnold', 'ombro', 'halter',
    'Sentado, halteres na frente do rosto com palmas viradas para voce.|Suba girando as maos ate as palmas ficarem para frente no topo.|Desca refazendo a rotacao.',
    'Girar rapido demais e perder a tensao.', 'triceps'],
  ['Desenvolvimento na maquina', 'ombro', 'maquina',
    'Ajuste o assento para as pegadas ficarem na altura dos ombros.|Costas apoiadas, empurre para cima sem travar os cotovelos.|Volte controlado.',
    'Assento baixo demais forcando o manguito.', 'triceps'],
  ['Elevacao lateral com halteres', 'ombro', 'halter',
    'Em pe, halteres ao lado do corpo, cotovelos levemente flexionados.|Suba pelos lados ate a altura dos ombros, liderando com o cotovelo.|Desca bem devagar, resistindo a gravidade.',
    'Usar impulso de tronco.|Subir acima da linha do ombro (entra trapezio).|Girar o punho como se despejasse agua.', ''],
  ['Elevacao lateral no cabo', 'ombro', 'cabo',
    'Polia baixa, cabo passando na frente do corpo.|Eleve o braco lateralmente ate a altura do ombro.|Desca controlado mantendo tensao constante.',
    'Inclinar o corpo para o lado oposto.', ''],
  ['Elevacao frontal com halteres', 'ombro', 'halter',
    'Halteres a frente das coxas, palmas para baixo.|Eleve um braco (ou os dois) ate a altura dos olhos.|Desca controlado.',
    'Balancar o tronco.|Subir acima da cabeca sem necessidade.', ''],
  ['Elevacao frontal com anilha', 'ombro', 'anilha',
    'Segure a anilha nas laterais com os dois bracos estendidos.|Eleve ate a altura dos olhos.|Desca controlado ate a coxa.',
    'Usar impulso de quadril.', ''],
  ['Crucifixo inverso com halteres', 'ombro', 'halter',
    'Tronco inclinado a ~45 graus, halteres pendurados abaixo do peito.|Abra os bracos para os lados ate a linha dos ombros.|Contraia o deltoide posterior e volte controlado.',
    'Usar carga alta e virar remada.|Encolher os ombros.', 'costas'],
  ['Voador inverso na maquina', 'ombro', 'maquina',
    'Peito apoiado, pegue as alavancas com bracos semi-estendidos.|Abra para tras ate a linha dos ombros.|Segure a contracao e volte devagar.',
    'Dobrar os cotovelos durante o movimento.', 'costas'],
  ['Face pull no cabo', 'ombro', 'cabo',
    'Corda na polia alta, na altura do rosto. Pegada neutra.|Puxe a corda em direcao a testa, separando as maos.|Termine com os cotovelos altos e as maos ao lado da cabeca.',
    'Puxar como remada, com cotovelo baixo.|Usar carga alta demais.', 'costas'],
  ['Remada alta', 'ombro', 'barra',
    'Pegada pronada na largura dos ombros (nao muito fechada).|Puxe a barra ate a linha do peito, cotovelos acima das maos.|Desca controlado.',
    'Pegada muito fechada + subir alto demais (impacto no ombro).', 'costas'],

  /* ---------------------------- BICEPS ---------------------------- */
  ['Rosca direta com barra', 'biceps', 'barra',
    'Em pe, pegada supinada na largura dos ombros, cotovelos colados ao tronco.|Suba a barra ate a altura do peito contraindo o biceps.|Desca controlado ate quase estender.',
    'Balancar o tronco para dar impulso.|Mover os cotovelos para frente.', 'antebraco'],
  ['Rosca direta com barra W', 'biceps', 'barra',
    'Barra W na pegada media, punhos em posicao neutra confortavel.|Cotovelos fixos ao lado do corpo, suba contraindo.|Desca controlado.',
    'Afastar o cotovelo do corpo.', 'antebraco'],
  ['Rosca alternada com halteres', 'biceps', 'halter',
    'Em pe, halteres ao lado do corpo com palmas voltadas para dentro.|Suba um braco girando o punho para supinado no meio do caminho.|Contraia no topo e desca controlado. Alterne.',
    'Subir os dois ao mesmo tempo sem perceber.|Usar o ombro para elevar.', 'antebraco'],
  ['Rosca martelo', 'biceps', 'halter',
    'Pegada neutra (polegar para cima) o tempo todo.|Suba mantendo o cotovelo fixo ao lado do corpo.|Desca controlado.',
    'Girar o punho (vira rosca comum).', 'antebraco'],
  ['Rosca concentrada', 'biceps', 'halter',
    'Sentado, cotovelo apoiado na parte interna da coxa.|Suba o halter contraindo o biceps ate o limite.|Desca ate estender completamente.',
    'Tirar o cotovelo do apoio.', ''],
  ['Rosca Scott', 'biceps', 'barra',
    'Bracos apoiados no banco inclinado, axila encostada no topo.|Suba a barra contraindo, sem descolar os bracos.|Desca ate quase estender, controlando bem o final.',
    'Estender de forma explosiva no fim (risco de lesao no tendao).', ''],
  ['Rosca no cabo', 'biceps', 'cabo',
    'Polia baixa com barra reta ou W, cotovelos fixos.|Suba contraindo, aproveitando a tensao constante do cabo.|Desca controlado.',
    'Recuar o corpo para ajudar.', ''],
  ['Rosca inversa', 'biceps', 'barra',
    'Pegada pronada (palmas para baixo) na largura dos ombros.|Suba com cotovelos fixos ate a altura do peito.|Desca controlado.',
    'Usar carga alta demais - esse exercicio pede leve.', 'antebraco'],
  ['Rosca 21', 'biceps', 'barra',
    '7 repeticoes da parte baixa (ate 90 graus).|7 repeticoes da parte alta (de 90 graus ao topo).|7 repeticoes completas. Sem descanso entre as fases.',
    'Perder a postura na terceira fase.', ''],

  /* ---------------------------- TRICEPS ---------------------------- */
  ['Triceps testa com barra W', 'triceps', 'barra',
    'Deitado no banco, barra W acima do peito com bracos estendidos.|Dobre so os cotovelos, descendo a barra ate a testa ou pouco atras.|Estenda voltando a posicao inicial sem mover os ombros.',
    'Mover os cotovelos para frente e para tras.|Abrir os cotovelos.', ''],
  ['Triceps frances com halter', 'triceps', 'halter',
    'Sentado ou em pe, halter segurado com as duas maos acima da cabeca.|Desca atras da cabeca dobrando so os cotovelos.|Estenda contraindo o triceps.',
    'Abrir os cotovelos para os lados.|Arquear a lombar.', ''],
  ['Triceps pulley com corda', 'triceps', 'cabo',
    'Polia alta com corda, cotovelos colados ao tronco.|Estenda os bracos para baixo abrindo a corda no final.|Volte controlado ate 90 graus, sem deixar o cotovelo subir.',
    'Inclinar o corpo e empurrar com o peso do tronco.|Deixar os cotovelos vagarem para frente.', ''],
  ['Triceps pulley com barra', 'triceps', 'cabo',
    'Polia alta com barra reta, pegada pronada.|Cotovelos fixos, estenda ate embaixo.|Volte controlado ate 90 graus.',
    'Usar o corpo como alavanca.', ''],
  ['Triceps coice', 'triceps', 'halter',
    'Tronco inclinado, braco colado ao corpo com cotovelo a 90 graus.|Estenda o antebraco para tras ate travar o cotovelo.|Contraia 1 segundo e volte.',
    'Mover o ombro em vez do cotovelo.', ''],
  ['Mergulho no banco', 'triceps', 'peso-corporal',
    'Maos na borda do banco atras do corpo, pernas estendidas a frente.|Desca dobrando os cotovelos ate 90 graus, corpo rente ao banco.|Empurre para cima ate estender.',
    'Afastar o corpo do banco (sobrecarrega o ombro).', 'ombro'],
  ['Supino fechado', 'triceps', 'barra',
    'Deitado, pegada na largura dos ombros (nao mais fechada que isso).|Desca a barra ate a parte baixa do peito, cotovelos rentes ao corpo.|Empurre focando o triceps.',
    'Pegada fechada demais (dor no punho).|Abrir os cotovelos.', 'peito'],
  ['Triceps na maquina', 'triceps', 'maquina',
    'Ajuste o assento para o cotovelo alinhar com o eixo da maquina.|Estenda os bracos contraindo o triceps.|Volte controlado.',
    'Alinhamento errado do cotovelo com o eixo.', ''],

  /* ---------------------------- ANTEBRACO ---------------------------- */
  ['Rosca de punho', 'antebraco', 'barra',
    'Sentado, antebracos apoiados nas coxas, palmas para cima.|Deixe a barra rolar ate a ponta dos dedos e feche subindo o punho.|Amplitude curta e controlada.',
    'Mover o antebraco em vez do punho.', ''],
  ['Rosca de punho inversa', 'antebraco', 'barra',
    'Antebracos apoiados, palmas para baixo.|Eleve o dorso da mao contraindo o antebraco.|Desca controlado.',
    'Carga alta demais - esse pede pouco peso.', ''],
  ['Caminhada do fazendeiro', 'antebraco', 'halter',
    'Segure um halter pesado em cada mao, ombros para tras, abdomen firme.|Caminhe em linha reta com passos curtos e controlados.|Mantenha a postura ereta ate o fim da distancia.',
    'Curvar os ombros para frente.', 'corpo-inteiro'],

  /* ---------------------------- QUADRICEPS ---------------------------- */
  ['Agachamento livre', 'quadriceps', 'barra',
    'Barra apoiada no trapezio, pes na largura dos ombros, pontas levemente para fora.|Abdomen contraido, peito alto. Desca empurrando o quadril para tras e dobrando os joelhos.|Desca ate a coxa ficar pelo menos paralela ao chao.|Suba empurrando o chao com o meio do pe, joelhos alinhados com os pes.',
    'Joelhos colapsando para dentro.|Levantar os calcanhares.|Arredondar a lombar no fundo (butt wink excessivo).', 'gluteo,posterior,lombar'],
  ['Agachamento frontal', 'quadriceps', 'barra',
    'Barra na frente dos ombros, cotovelos bem altos.|Tronco o mais vertical possivel. Desca controlado.|Suba mantendo os cotovelos altos.',
    'Deixar os cotovelos caírem (a barra rola para frente).', 'gluteo,abdomen'],
  ['Agachamento no Smith', 'quadriceps', 'maquina',
    'Pes um pouco a frente da barra, apoiados no calcanhar.|Desca ate a coxa passar da paralela.|Suba empurrando com o calcanhar.',
    'Pes muito atras, forcando o joelho.', 'gluteo'],
  ['Leg press 45', 'quadriceps', 'maquina',
    'Pes na plataforma na largura dos ombros, meio da plataforma.|Desca ate o joelho formar ~90 graus, sem descolar o quadril do banco.|Empurre sem travar completamente os joelhos.',
    'Descer demais e arredondar a lombar.|Travar o joelho no topo.', 'gluteo'],
  ['Cadeira extensora', 'quadriceps', 'maquina',
    'Ajuste o encosto para o joelho alinhar com o eixo da maquina.|Estenda as pernas ate quase travar, contraindo o quadriceps.|Desca controlado sem deixar o peso bater.',
    'Usar impulso e balancar.|Levantar o quadril do banco.', ''],
  ['Hack squat', 'quadriceps', 'maquina',
    'Costas coladas no encosto, pes na largura dos ombros.|Desca ate a coxa passar da paralela.|Empurre com o calcanhar sem travar o joelho.',
    'Descolar a lombar do encosto no fundo.', 'gluteo'],
  ['Afundo com halteres', 'quadriceps', 'halter',
    'Em pe com um halter em cada mao. De um passo a frente.|Desca ate o joelho de tras quase encostar no chao.|Empurre com o calcanhar da perna da frente para voltar.',
    'Passo curto demais (joelho passa muito da ponta do pe).|Inclinar o tronco.', 'gluteo'],
  ['Passada (walking lunge)', 'quadriceps', 'halter',
    'Halteres ao lado do corpo. De um passo longo a frente e desca.|Empurre com a perna da frente e traga a de tras para o proximo passo.|Mantenha o tronco ereto durante toda a caminhada.',
    'Perder o equilibrio olhando para baixo.', 'gluteo'],
  ['Agachamento bulgaro', 'quadriceps', 'halter',
    'Pe de tras apoiado num banco, pe da frente a um passo largo.|Desca verticalmente ate a coxa da frente ficar paralela.|Empurre com o calcanhar da frente para subir.',
    'Pe da frente muito perto do banco.|Empurrar com a perna de tras.', 'gluteo'],
  ['Agachamento goblet', 'quadriceps', 'halter',
    'Segure um halter verticalmente junto ao peito.|Pes na largura dos ombros, desca entre os joelhos.|Suba mantendo o peito alto.',
    'Deixar o halter afastar do corpo.', 'gluteo'],

  /* ---------------------------- POSTERIOR ---------------------------- */
  ['Mesa flexora', 'posterior', 'maquina',
    'Deitado de bruços, rolo logo acima do calcanhar.|Flexione os joelhos trazendo o rolo ate o gluteo.|Desca controlado ate quase estender.',
    'Levantar o quadril da mesa.|Descer o peso rapido.', ''],
  ['Cadeira flexora sentada', 'posterior', 'maquina',
    'Sentado, rolo acima do calcanhar, coxas travadas.|Flexione os joelhos empurrando o rolo para baixo e para tras.|Volte controlado.',
    'Deslizar o quadril no banco.', ''],
  ['Stiff com barra', 'posterior', 'barra',
    'Pes na largura do quadril, joelhos levemente flexionados e FIXOS.|Empurre o quadril para tras deslizando a barra rente as pernas.|Desca ate sentir o alongamento do posterior, coluna neutra.|Volte estendendo o quadril e contraindo o gluteo.',
    'Dobrar os joelhos durante o movimento (vira terra).|Arredondar a lombar.|Afastar a barra do corpo.', 'gluteo,lombar'],
  ['Terra romeno com halteres', 'posterior', 'halter',
    'Halteres a frente das coxas, joelhos semi-flexionados fixos.|Empurre o quadril para tras descendo os halteres rente as pernas.|Suba contraindo gluteo e posterior.',
    'Transformar em agachamento.', 'gluteo'],
  ['Bom dia', 'posterior', 'barra',
    'Barra no trapezio, pes na largura do quadril.|Empurre o quadril para tras inclinando o tronco ate ~45 graus.|Coluna neutra o tempo todo. Volte estendendo o quadril.',
    'Carga alta demais nesse exercicio.|Arredondar a coluna.', 'lombar,gluteo'],
  ['Nordic curl', 'posterior', 'peso-corporal',
    'Ajoelhado com os tornozelos presos, corpo em linha reta do joelho a cabeca.|Desca o mais devagar possivel controlando com o posterior.|Empurre o chao com as maos para voltar, se precisar.',
    'Dobrar o quadril durante a descida.', ''],

  /* ---------------------------- GLUTEO ---------------------------- */
  ['Elevacao pelvica (hip thrust)', 'gluteo', 'barra',
    'Costas apoiadas no banco na linha das escapulas, barra sobre o quadril com protecao.|Pes na largura do quadril, canela vertical no topo.|Suba estendendo o quadril ate o tronco ficar paralelo ao chao.|Contraia o gluteo 1 segundo no topo e desca controlado.',
    'Hiperextender a lombar em vez de estender o quadril.|Pes muito longe ou muito perto.', 'posterior'],
  ['Ponte de gluteo', 'gluteo', 'peso-corporal',
    'Deitado de costas, joelhos dobrados, pes no chao perto do gluteo.|Empurre o chao com os calcanhares e suba o quadril.|Contraia o gluteo no topo e desca controlado.',
    'Empurrar com a lombar.', 'posterior'],
  ['Coice na polia', 'gluteo', 'cabo',
    'Caneleira no tornozelo, polia baixa. Tronco levemente inclinado a frente.|Estenda o quadril levando a perna para tras e para cima.|Contraia o gluteo no topo e volte controlado.',
    'Arquear a lombar para ganhar amplitude.', ''],
  ['Abducao na maquina', 'gluteo', 'maquina',
    'Sentado, joelhos contra os apoios.|Abra as pernas contra a resistencia ate o limite confortavel.|Segure 1 segundo e volte devagar.',
    'Jogar o tronco para tras para abrir mais.', ''],
  ['Abducao com elastico', 'gluteo', 'elastico',
    'Elastico acima dos joelhos, de pe ou em posicao de mini-agachamento.|De passos laterais mantendo tensao constante no elastico.|Nao deixe os joelhos colapsarem para dentro.',
    'Perder a tensao do elastico entre os passos.', ''],
  ['Agachamento sumo com halter', 'gluteo', 'halter',
    'Pes bem afastados, pontas para fora ~45 graus. Halter entre as pernas.|Desca mantendo o tronco vertical e os joelhos alinhados com os pes.|Suba contraindo o gluteo no topo.',
    'Joelhos colapsando para dentro.', 'quadriceps'],
  ['Step up no banco', 'gluteo', 'halter',
    'Halteres nas maos, um pe todo apoiado no banco.|Suba empurrando com o calcanhar da perna de cima, sem impulso da de baixo.|Desca controlado com a mesma perna.',
    'Dar impulso com a perna de tras.', 'quadriceps'],

  /* ---------------------------- PANTURRILHA ---------------------------- */
  ['Panturrilha em pe na maquina', 'panturrilha', 'maquina',
    'Ponta dos pes na plataforma, calcanhar livre.|Desca o calcanhar ate sentir o alongamento maximo.|Suba na ponta dos pes contraindo forte 1 segundo.',
    'Amplitude curta, so quicando.|Dobrar os joelhos.', ''],
  ['Panturrilha sentado', 'panturrilha', 'maquina',
    'Sentado com o rolo sobre os joelhos, ponta dos pes na plataforma.|Desca o calcanhar ao maximo e suba contraindo.|Pausa de 1 segundo no topo.',
    'Fazer rapido demais sem contracao.', ''],
  ['Panturrilha no leg press', 'panturrilha', 'maquina',
    'Ponta dos pes na borda inferior da plataforma.|Empurre estendendo o tornozelo ao maximo.|Volte deixando o calcanhar descer bem.',
    'Travar os joelhos.', ''],
  ['Panturrilha unilateral com halter', 'panturrilha', 'halter',
    'Um pe num step, halter na mao do mesmo lado.|Desca o calcanhar ate o alongamento maximo.|Suba na ponta do pe e contraia.',
    'Se apoiar demais na mao livre.', ''],

  /* ---------------------------- ABDOMEN ---------------------------- */
  ['Abdominal supra (crunch)', 'abdomen', 'peso-corporal',
    'Deitado, joelhos dobrados, maos ao lado da cabeca (sem puxar o pescoco).|Enrole a coluna tirando as escapulas do chao.|Contraia o abdomen no topo e desca controlado.',
    'Puxar a cabeca com as maos.|Fazer flexao de quadril em vez de enrolar a coluna.', ''],
  ['Elevacao de pernas deitado', 'abdomen', 'peso-corporal',
    'Deitado, maos sob o gluteo para proteger a lombar.|Suba as pernas ate a vertical mantendo a lombar colada no chao.|Desca controlado sem deixar a lombar arquear.',
    'Deixar a lombar descolar do chao.', ''],
  ['Prancha', 'abdomen', 'peso-corporal',
    'Antebracos no chao, cotovelos sob os ombros, corpo em linha reta.|Contraia abdomen e gluteo, respire normalmente.|Segure o tempo programado sem deixar o quadril cair ou subir.',
    'Quadril alto demais (vira descanso).|Lombar arqueada.', ''],
  ['Prancha lateral', 'abdomen', 'peso-corporal',
    'Apoiado num antebraco, corpo em linha reta de lado.|Quadril elevado, sem cair para o chao.|Segure o tempo e troque de lado.',
    'Girar o tronco para frente.', ''],
  ['Abdominal na polia ajoelhado', 'abdomen', 'cabo',
    'Ajoelhado de costas para a polia alta, corda ao lado da cabeca.|Enrole a coluna trazendo os cotovelos em direcao as coxas.|Volte controlado sem perder a tensao.',
    'Puxar com os bracos em vez do abdomen.|Mover o quadril.', ''],
  ['Elevacao de pernas na barra', 'abdomen', 'peso-corporal',
    'Pendurado na barra, ombros ativos (nao relaxe totalmente).|Suba as pernas ate acima da linha do quadril, enrolando a pelve.|Desca controlado sem balancar.',
    'Balancar o corpo usando impulso.|Parar a 90 graus sem enrolar a pelve.', ''],
  ['Russian twist', 'abdomen', 'anilha',
    'Sentado, tronco inclinado a ~45 graus, pes elevados ou no chao.|Gire o tronco levando o peso de um lado ao outro.|Controle a rotacao, sem so mover os bracos.',
    'Mover so os bracos sem girar o tronco.', ''],
  ['Abdominal bicicleta', 'abdomen', 'peso-corporal',
    'Deitado, maos ao lado da cabeca, pernas elevadas.|Leve o cotovelo em direcao ao joelho oposto girando o tronco.|Alterne de forma controlada, sem pressa.',
    'Fazer rapido demais sem contrair.', ''],
  ['Ab wheel', 'abdomen', 'outro',
    'Ajoelhado, roda no chao a frente dos ombros.|Role para frente mantendo a lombar neutra e o abdomen firme.|Va so ate onde consegue manter a lombar reta e volte.',
    'Deixar a lombar arquear (dor lombar garantida).', 'lombar'],
  ['Dead bug', 'abdomen', 'peso-corporal',
    'Deitado, bracos apontando para o teto, joelhos a 90 graus.|Estenda o braco e a perna opostos ate quase o chao.|Lombar sempre colada no chao. Volte e alterne.',
    'Descolar a lombar do chao.', ''],

  /* ---------------------------- LOMBAR ---------------------------- */
  ['Hiperextensao lombar', 'lombar', 'maquina',
    'Banco romano com o apoio na altura do quadril.|Desca flexionando o quadril com a coluna neutra.|Suba ate o corpo ficar alinhado, sem hiperextender.',
    'Passar da linha reta no topo.|Arredondar a coluna na descida.', 'posterior,gluteo'],
  ['Superman', 'lombar', 'peso-corporal',
    'Deitado de bruços, bracos estendidos a frente.|Eleve bracos, peito e pernas ao mesmo tempo.|Segure 2 segundos e desca controlado.',
    'Jogar a cabeca para tras.', 'gluteo'],

  /* ---------------------------- CARDIO ---------------------------- */
  ['Caminhada inclinada na esteira', 'cardio', 'cardio',
    'Inclinacao entre 8 e 15%, velocidade entre 4,5 e 6 km/h.|Nao segure no apoio - deixe os bracos livres.|Mantenha o ritmo em que ainda consegue falar frases curtas.',
    'Segurar no corrimao (derruba o gasto calorico).', ''],
  ['Corrida na esteira', 'cardio', 'cardio',
    'Aqueca 5 minutos caminhando antes de correr.|Pisada no meio do pe, tronco ereto, passada curta.|Termine com 3-5 minutos de caminhada para desacelerar.',
    'Comecar sem aquecimento.', ''],
  ['Bicicleta ergometrica', 'cardio', 'cardio',
    'Ajuste o banco: joelho quase estendido no ponto mais baixo do pedal.|Mantenha cadencia constante entre 70 e 90 rpm.|Ajuste a carga para manter o esforco alvo.',
    'Banco baixo demais (dor no joelho).', ''],
  ['Eliptico', 'cardio', 'cardio',
    'Postura ereta, use os bracos ativamente.|Mantenha o pe todo apoiado no pedal.|Ritmo constante pelo tempo programado.',
    'Apoiar o peso nos bracos.', ''],
  ['Escada (stair)', 'cardio', 'cardio',
    'Postura ereta, sem se apoiar no corrimao.|Pise com o pe inteiro no degrau.|Ritmo constante e respiracao controlada.',
    'Pendurar-se no apoio.', 'gluteo'],
  ['Pular corda', 'cardio', 'cardio',
    'Corda na altura certa: pisando no meio, as pontas chegam nas axilas.|Saltos baixos, girando pelo punho e nao pelo ombro.|Aterrisse na ponta dos pes com joelhos macios.',
    'Saltar alto demais e cansar rapido.', 'panturrilha'],
  ['Remo ergometro', 'cardio', 'cardio',
    'Sequencia: pernas, quadril, bracos. Volta: bracos, quadril, pernas.|Coluna neutra, sem arredondar nas costas.|Puxe a alca ate a base do peito.',
    'Puxar com os bracos primeiro.|Arredondar a lombar.', 'costas'],
  ['Burpee', 'cardio', 'peso-corporal',
    'Agache, apoie as maos no chao e jogue os pes para tras.|Faca uma flexao, traga os pes de volta.|Salte para cima com os bracos estendidos.',
    'Deixar o quadril cair na flexao.', 'corpo-inteiro'],

  /* ---------------------------- CORPO INTEIRO ---------------------------- */
  ['Kettlebell swing', 'corpo-inteiro', 'kettlebell',
    'Pes na largura dos ombros, kettlebell no chao a frente.|Quadril para tras, pegue o peso e balance entre as pernas.|Estenda o quadril com forca projetando o peso ate a altura do peito.|O movimento vem do quadril, nao dos bracos.',
    'Agachar em vez de empurrar o quadril.|Levantar o peso com os bracos.', 'gluteo,posterior'],
  ['Thruster', 'corpo-inteiro', 'barra',
    'Barra na frente dos ombros, cotovelos altos.|Agache ate abaixo da paralela.|Suba explosivo e emende o desenvolvimento acima da cabeca em um movimento so.',
    'Separar o agachamento do desenvolvimento.', 'quadriceps,ombro'],
  ['Clean and press', 'corpo-inteiro', 'barra',
    'Puxe a barra do chao com extensao explosiva de quadril.|Receba a barra na frente dos ombros com cotovelos altos.|Empurre acima da cabeca e desca controlado.',
    'Puxar com os bracos em vez do quadril.', 'ombro,costas'],
  ['Snatch com halter', 'corpo-inteiro', 'halter',
    'Halter entre os pes, quadril para tras, coluna neutra.|Extensao explosiva de quadril levando o halter acima da cabeca em um movimento.|Estabilize no topo e desca controlado.',
    'Fazer com carga alta antes de dominar a tecnica.', 'ombro'],

  /* ---------------------------- EM CASA / PESO CORPORAL ---------------------------- */
  ['Agachamento peso corporal', 'quadriceps', 'peso-corporal',
    'Pes na largura dos ombros, pontas levemente para fora, bracos a frente para equilibrio.|Desca empurrando o quadril para tras ate a coxa passar da paralela.|Suba empurrando o chao com o calcanhar, sem deixar o joelho cair para dentro.',
    'Calcanhar saindo do chao.|Amplitude curta, parando no meio.', 'gluteo'],
  ['Afundo sem peso', 'quadriceps', 'peso-corporal',
    'Em pe, maos na cintura. De um passo longo a frente.|Desca ate o joelho de tras quase encostar no chao.|Empurre com o calcanhar da frente para voltar. Alterne as pernas.',
    'Passo curto demais.|Inclinar o tronco para frente.', 'gluteo'],
  ['Agachamento com salto', 'quadriceps', 'peso-corporal',
    'Agache ate a coxa ficar paralela ao chao.|Salte com forca estendendo quadril e joelhos.|Aterrisse na ponta do pe e desca macio, absorvendo o impacto.',
    'Aterrissar de perna travada (impacto direto no joelho).', 'panturrilha,cardio'],
  ['Polichinelo', 'cardio', 'peso-corporal',
    'Em pe, pes juntos e bracos ao lado do corpo.|Salte abrindo as pernas e levando os bracos acima da cabeca.|Volte a posicao inicial no mesmo ritmo. Mantenha a respiracao constante.',
    'Perder o ritmo e virar movimento solto.', 'corpo-inteiro'],
  ['Mountain climber', 'abdomen', 'peso-corporal',
    'Posicao de flexao, maos sob os ombros, corpo em linha reta.|Traga um joelho em direcao ao peito e volte, alternando rapido.|Quadril estavel, sem subir nem descer.',
    'Levantar o quadril e virar exercicio de ombro.', 'cardio'],
  ['Elevacao de joelhos no lugar', 'cardio', 'peso-corporal',
    'Em pe, corra no lugar levando o joelho ate a altura do quadril.|Apoie na ponta do pe, tronco ereto, abdomen firme.|Use os bracos no ritmo da corrida.',
    'Joelho baixo demais, sem elevar de verdade.', 'abdomen'],
  ['Flexao diamante', 'triceps', 'peso-corporal',
    'Maos juntas embaixo do peito formando um triangulo com polegares e indicadores.|Desca com os cotovelos rentes ao corpo.|Empurre focando o triceps, corpo sempre em linha reta.',
    'Abrir os cotovelos (perde o foco no triceps).|Deixar o quadril cair.', 'peito'],
  ['Remada invertida', 'costas', 'peso-corporal',
    'Deite sob uma barra baixa ou mesa firme, pegue na largura dos ombros.|Corpo em linha reta, calcanhares no chao.|Puxe o peito ate a barra juntando as escapulas e desca controlado.',
    'Deixar o quadril cair.|Amplitude curta.', 'biceps'],
  ['Panturrilha em pe sem peso', 'panturrilha', 'peso-corporal',
    'Em pe, ponta dos pes num degrau ou no chao mesmo.|Suba na ponta dos pes ao maximo e segure 1 segundo.|Desca devagar ate o alongamento completo.',
    'Fazer rapido e sem contracao no topo.', ''],
  ['Prancha com toque no ombro', 'abdomen', 'peso-corporal',
    'Posicao de prancha alta, maos sob os ombros, pes um pouco afastados.|Toque o ombro oposto com uma mao sem girar o quadril.|Alterne de forma lenta e controlada.',
    'Balancar o quadril a cada toque.', 'ombro'],
  ['Bird dog', 'lombar', 'peso-corporal',
    'De quatro, maos sob os ombros e joelhos sob o quadril.|Estenda o braco e a perna opostos ate a linha do corpo.|Segure 2 segundos e volte. Coluna sempre neutra.',
    'Arquear a lombar ao estender a perna.', 'abdomen,gluteo'],
  ['Corrida ao ar livre', 'cardio', 'cardio',
    'Aqueca 5 minutos caminhando.|Pisada no meio do pe, tronco ereto, passada curta e constante.|Termine com 3 a 5 minutos de caminhada para desacelerar.',
    'Sair correndo forte sem aquecer.', ''],
  ['Caminhada rapida', 'cardio', 'cardio',
    'Ritmo em que voce ainda consegue falar frases curtas, mas nao cantar.|Postura ereta, bracos balancando naturalmente.|Mantenha o ritmo constante pelo tempo programado.',
    'Ritmo tao leve que nao muda a respiracao.', ''],
  ['Mobilidade e alongamento', 'corpo-inteiro', 'peso-corporal',
    'Passe por quadril, tornozelo, coluna toracica e ombro.|Segure cada posicao de 30 a 45 segundos, respirando fundo.|Nunca force ate a dor - so ate o desconforto leve.',
    'Alongar musculo frio antes de treino pesado.', ''],
]

export const EXERCICIOS_SEED: Exercicio[] = L.map(([nome, grupo, equipamento, exec, erros, sec]) => ({
  id: 'ex_' + nome.toLowerCase()
    .normalize('NFD').replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''),
  nome,
  grupo,
  equipamento,
  execucao: exec.split('|').filter(Boolean),
  erros: erros ? erros.split('|').filter(Boolean) : [],
  gruposSecundarios: sec ? (sec.split(',').filter(Boolean) as GrupoMuscular[]) : [],
  custom: false,
  atualizadoEm: 0,
}))

/** Cores solidas e dessaturadas - separam os grupos sem virar neon. */
export const GRUPOS: { id: GrupoMuscular; nome: string; cor: string }[] = [
  { id: 'peito', nome: 'Peito', cor: '#c96a4a' },
  { id: 'costas', nome: 'Costas', cor: '#5a8cbf' },
  { id: 'ombro', nome: 'Ombro', cor: '#c9a049' },
  { id: 'biceps', nome: 'Biceps', cor: '#4fa385' },
  { id: 'triceps', nome: 'Triceps', cor: '#9b7fc7' },
  { id: 'antebraco', nome: 'Antebraco', cor: '#8592a5' },
  { id: 'quadriceps', nome: 'Quadriceps', cor: '#c25f70' },
  { id: 'posterior', nome: 'Posterior', cor: '#bd7095' },
  { id: 'gluteo', nome: 'Gluteo', cor: '#c2854e' },
  { id: 'panturrilha', nome: 'Panturrilha', cor: '#8ba055' },
  { id: 'abdomen', nome: 'Abdomen', cor: '#4f9aad' },
  { id: 'lombar', nome: 'Lombar', cor: '#7b81be' },
  { id: 'cardio', nome: 'Cardio', cor: '#c06a6a' },
  { id: 'corpo-inteiro', nome: 'Corpo inteiro', cor: '#a86eaf' },
]

export const EQUIPAMENTOS: { id: Equipamento; nome: string }[] = [
  { id: 'barra', nome: 'Barra' },
  { id: 'halter', nome: 'Halter' },
  { id: 'maquina', nome: 'Maquina' },
  { id: 'cabo', nome: 'Cabo/Polia' },
  { id: 'peso-corporal', nome: 'Peso corporal' },
  { id: 'kettlebell', nome: 'Kettlebell' },
  { id: 'elastico', nome: 'Elastico' },
  { id: 'anilha', nome: 'Anilha' },
  { id: 'cardio', nome: 'Cardio' },
  { id: 'outro', nome: 'Outro' },
]

export const nomeGrupo = (g: GrupoMuscular) => GRUPOS.find(x => x.id === g)?.nome ?? g
export const corGrupo = (g: GrupoMuscular) => GRUPOS.find(x => x.id === g)?.cor ?? '#8b98a9'
export const nomeEquip = (e: Equipamento) => EQUIPAMENTOS.find(x => x.id === e)?.nome ?? e
